routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!  
|
*/

Route::get('/', 'AttendanceController@index1');

Auth::routes(['verify' => true]);
Route::get('/logout', function(){
    Auth::logout();
    return Redirect::to('login');
 });

 /**
 * Password Reset Route(S)
 */
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

/**
 * Email Verification Route(s)
 */
Route::get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
Route::get('email/verify/{id}', 'Auth\VerificationController@verify')->name('verification.verify');
Route::get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');




 Route::get('/verify','HomeController@verify');
 Route::get('/user/verify/{token}', 'Auth\RegisterController@verifyUser');
 Route::get('/edit-profile','UsersController@edit');
 Route::get('/update-profile','UsersController@update');


Route::get('/home', 'HomeController@index')->name('home');
Route::get('comments','HomeController@comments');
Route::get('comment_back','HomeController@comment_back');

// Socialite Routes
Route::get('login/github', 'Auth\LoginController@redirectToProvider');
Route::get('login/github/callback', 'Auth\LoginController@handleProviderCallback');  
Route::get('add-about', 'HomeController@addAbout');    
Route::get('add-high-school', 'HomeController@addHighSchool');
Route::get('add-intermediate', 'HomeController@addIntermediate');
Route::get('add-graduation', 'HomeController@addGraduation');
Route::get('add-master', 'HomeController@addMaster');
Route::get('add-diploma', 'HomeController@addDiploma');
Route::get('add-experience', 'ExperienceController@addExperience');
Route::get('add-skills', 'HomeController@addSkills');
Route::get('update-about', 'HomeController@updateAbout');

// Attendance
Route::get('load-attandance', 'AttendanceController@index');
Route::get('make-attandance', 'AttendanceController@create');


Route::resource('tasks', 'AttendanceController');
Route::get('view-resume', 'HomeController@resumeOutput');

// Notes
Route::get('notes', 'NotesController@index');
Route::get('save-note', 'NotesController@storeNote');
Route::get('delete-note/{id}', 'NotesController@delete'); 
Route::get('update-note/{id}', 'NotesController@update');
Route::get('change-status/{id}', 'NotesController@changeStatus');
Route::get('change-status-undone/{id}', 'NotesController@changeStatusUndone');
Route::post('filter-notes', 'NotesController@filter'); 

//QR scanner
Route::get('qr-scanner', 'QrController@index');
Route::get('qr-code', function () {
    return QrCode::size(500)->generate('Welcome to kerneldev.com!');
});
Route::post('generate-qr-scanner', 'QrController@generate');
Route::get('scanner', 'QrController@scan');


Route::post('send-query', 'UsersController@query'); 


Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

resources/views/attendance.blade.php
@extends('master')
@section('title')
    Attendance
@endsection
@section('content')
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.min.css' />
{{-- <div class="container" > --}}
    <div class="profile-content section" >
        <div class="container">
          <div class="row" style="margin-top:10%">
              <div class="col-md-3">
                  <div class="profile-picture">
                
                          <div class="wrapper1">
                              <div class="profile-card js-profile-card">
                                <div class="profile-card__img">
                                  {{-- <img src="https://res.cloudinary.com/muhammederdem/image/upload/v1537638518/Ba%C5%9Fl%C4%B1ks%C4%B1z-1.jpg" alt="profile card"> --}}
                                  @if(Auth::user()->image=='#')
                                      <img src="{{asset("images/user/user_male.png")}}" class="img-circle img-responsive img-no-padding" alt="{!! Auth::user()->name !!}">
                                  @else
                                      <img src="{!! Auth::user()->image !!}" class="img-circle img-responsive img-no-padding" alt="{!! Auth::user()->name !!}">
                                  @endif
                                </div>
                            
                                <div class="profile-card__cnt js-profile-cnt">
                                  <div class="profile-card__name">
                                      {{Auth::user()->name}}
                                   </div>
                                  <div class="profile-card__txt">{{Auth::user()->job}} </div>
                                  <div class="profile-card-loc">
                                    <i class="fa fa-map-marker"></i>
                                    <span class="profile-card-loc__txt">
                                      {{Auth::user()->city}}
                                    </span>
                                  </div>
                            
                            
                            
                                  <div class="profile-card-ctr">
                                      <a href="#">
                                          <button class="profile-card__button button--blue"><i class="fa fa-upload"></i>Upload Picture </button>
                                      </a>
                                      <a href="#">
                                          <button class="profile-card__button button--orange"><i class="fa fa-download"></i>Download </button>
                                      </a>
                                     
                                  </div>
                                </div>
                            
                              </div>
                            
                            </div>
                            
                      
                  </div>
              </div>
              
              <div class="col-md-9">
                    @if (Session::has('success'))
                        <div class="alert alert-success alert-with-icon" data-notify="container">
                            <div class="container">
                            <div class="alert-wrapper">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <i class="nc-icon nc-simple-remove"></i>
                                </button>
                                <div class="message"><i class="nc-icon nc-bell-55"></i> {!! \Session::get('success') !!}</div>
                                </div>
                            </div>
                        </div>
                    @endif
                <div class="row">
                    <div id='calendar'></div>
                </div>
              </div>
          </div>
          
        </div>
      </div>
    {{-- </div> --}}
@stop


@push('scripts')
<script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.min.js'></script>
<script>
    $(document).ready(function() {
        // page is now ready, initialize the calendar...
        $('#calendar').fullCalendar({
            // put your options and callbacks here
            events : [
                @foreach($data as $dat)
                {
                    title : '{{ $dat->id }}',
                    start : '{{ $dat->created_at }}',
                    url : '{{ route('tasks.edit', $dat->id) }}'
                },
                @endforeach
            ]
        })
    });
</script>
@endpush

resources/views/comments.blade.php
@extends('master_user')
@section('title')
Comments
@stop
@section('content')
<main>

    <!-- Container -->
    <div class="container scrollspy" id="started-section">

       

        <!-- Section About -->
        <div class="section about scrollspy" id="about-section">

            <!-- Title -->
            <div class="row">
                <div class="col s12 m12 l12">
                    <h5 class="grey-text text-darken-2 left-align">Comments</h5>
                </div>
            </div>
      
            <div class="row">
                <div class="col s12 m12 l12">
                    <div class="card-panel">
                        <div class="text-box">
                            <?php $comments = App\TestComment::get(); 
                            // dd($comment);
                            ?>
                            
                            @comments(['model' => $comments])
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</main>
@endsection

resources/views/edit_profile.blade.php
@extends('master1')
@section('title')
    Edit Profile
@endsection
@section('content')

{{-- <div class="container" > --}}
    <div class="profile-content section" >
      <div class="container">
        <div class="row" style="margin-top:10%">
            <div class="col-md-3">
                <div class="profile-picture">
                    
                        {{-- <div class="our-team">
                            <div class="picture">
                                @if(Auth::user()->image=='#')
                                    <img src="{{asset("images/user/user_male.png")}}" class="img-circle img-responsive img-no-padding" alt="{!! Auth::user()->name !!}">
                                @else
                                    <img src="{!! Auth::user()->image !!}" class="img-circle img-responsive img-no-padding" alt="{!! Auth::user()->name !!}">
                                @endif
                            </div>
                          <div class="team-content">
                            <h4 class="title text-center">{{Auth::user()->name}}
                                <br />
                                <small>{{Auth::user()->job}}</small>
                                </h4>
                          </div>
                          <ul class="social">
                            <li><a href="https://codepen.io/collection/XdWJOQ/" class="fa fa-facebook" aria-hidden="true"></a></li>
                            <li><a href="https://codepen.io/collection/XdWJOQ/" class="fa fa-twitter" aria-hidden="true"></a></li>
                            <li><a href="https://codepen.io/collection/XdWJOQ/" class="fa fa-google-plus" aria-hidden="true"></a></li>
                            <li><a href="https://codepen.io/collection/XdWJOQ/" class="fa fa-linkedin" aria-hidden="true"></a></li>
                          </ul>
                        </div> --}}
                        <div class="wrapper1">
                            <div class="profile-card js-profile-card">
                              <div class="profile-card__img">
                                @if(Auth::user()->image=='#')
                                    <img src="{{asset("images/user/user_male.png")}}" class="img-circle img-responsive img-no-padding" alt="{!! Auth::user()->name !!}">
                                @else
                                    <img src="{{ asset( Auth::user()->image )}}" class="img-circle img-responsive img-no-padding" alt="{!! Auth::user()->name !!}">
                                @endif
                              </div>
                          
                              <div class="profile-card__cnt js-profile-cnt">
                                <div class="profile-card__name">
                                    {{Auth::user()->name}}
                                 </div>
                                <div class="profile-card__txt">{{Auth::user()->job}} </div>
                                <div class="profile-card-loc">
                                  <i class="fa fa-map-marker"></i>
                                  <span class="profile-card-loc__txt">
                                    {{Auth::user()->city}}
                                  </span>
                                </div>
                          
                                <div class="profile-card-ctr">
                                    <a href="#">
                                        <button class="profile-card__button button--blue"><i class="fa fa-upload"></i>Upload Picture </button>
                                    </a>
                                    <a href="#">
                                        <button class="profile-card__button button--orange"><i class="fa fa-download"></i>Download </button>
                                    </a>
                                   
                                </div>
                              </div>
                          
                            </div>
                          
                          </div>
                          
                    
                </div>
            </div>
            
            <div class="col-md-9">
                @if (Session::has('success'))
                    <div class="alert alert-success alert-with-icon" data-notify="container">
                        <div class="container">
                        <div class="alert-wrapper">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <i class="nc-icon nc-simple-remove"></i>
                            </button>
                            <div class="message"><i class="nc-icon nc-bell-55"></i> {!! \Session::get('success') !!}</div>
                            </div>
                        </div>
                    </div>
                @endif
                <form action="update-profile">
                    <div class="row">
                        <div class="col-md-6">
                            <label for="">Name</label>
                        <input type="text" class="form-control" name="name" value="{{ Auth::user()->name }}">
                        </div>
                        <div class="col-md-6">
                            <label for="">Father name</label>
                            <input type="text" class="form-control" name="father_name" value="{{ Auth::user()->father_name }}">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label for=""><i class="fa fa-envelope"></i> Email</label>
                            <input type="text" class="form-control" disabled value="{{ Auth::user()->email }}">
                        </div>
                        <div class="col-md-6">
                            <label for=""><i class="fa fa-mobile"></i> Mobile</label>
                            <input type="text" class="form-control" name="mobile" value="{{ Auth::user()->mobile }}">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <h3>Social links</h3>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label for=""><i class="fa fa-facebook"></i> Facebook</label>
                            <input type="text" class="form-control" name="facebook_link" value="{{ Auth::user()->facebook_url }}">
                        </div>
                        <div class="col-md-6">
                            <label for=""><i class="fa fa-instagram"></i> Instagram</label>
                            <input type="text" class="form-control" name="instagram_link" value="{{ Auth::user()->instagram_url }}">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label for=""><i class="fa fa-linkedin"></i> Linkedin</label>
                            <input type="text" class="form-control" name="linkedin_url" value="{{ Auth::user()->linkedin_url }}">
                        </div>
                        <div class="col-md-6">
                            <label for=""><i class="fa fa-twitter"></i> Twitter</label>
                            <input type="text" class="form-control" name="twitter_url" value="{{ Auth::user()->twitter_url }}">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <label for=""><i class="fa fa-globe"></i> Website</label>
                            <input type="text" class="form-control" name="website" value="{{ Auth::user()->website }}">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <label for=""><i class="fa fa-user"></i> Age</label>
                            <input type="text" class="form-control" name="age" value="{{ Auth::user()->age }}">
                        </div>
                        <div class="col-md-6">
                            <label for=""><i class="fa fa-briefcase"></i> Current Job Role</label>
                            <input type="text" class="form-control" name="job" value="{{ Auth::user()->job }}">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <label for=""><i class="fa fa-user"></i> About</label>
                            <textarea name="about" id="" class="form-control" namne="about">{{ Auth::user()->about }}</textarea>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <label for=""><i class="fa fa-address-card"></i> Permanent Address</label>
                            <textarea name="about" class="form-control" namne="about" id="permanent_address">{{ Auth::user()->permanent_address }}</textarea>
                        </div>
                    </div><br>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-check">
                                <label class="form-check-label">
                                <input class="form-check-input text-success" type="checkbox" value="" onclick="copyAddress()"> Current address same as Permanent address
                                <span class="form-check-sign"></span>
                                </label>
                            </div>
                            
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <label for=""><i class="fa fa-address-card"></i> Current Address</label>
                            <textarea name="about" class="form-control" namne="about" id="current_address">{{ Auth::user()->current_address }}</textarea>
                        </div>
                    </div>
                    <br><div class="row">
                        <div class="col-md-12">
                            <h3 class="text-center"><button type="submit" class="btn btn-success">Save</button></h3>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        
      </div>
    </div>
  {{-- </div> --}}

@endsection
@push('scripts')
    <script>
    // var a=["http://www.sample.com","https://www.sample.com/","https://www.sample.com#","http://www.sample.com/xyz","http://www.sample.com/#xyz","www.sample.com","www.sample.com/xyz/#/xyz","sample.com","sample.com?name=foo","http://www.sample.com#xyz","http://www.sample.c"];
    // var re=/^((https?|ftp|smtp):\/\/)?(www.)?[a-z0-9]+(\.[a-z]{2,}){1,3}(#?\/?[a-zA-Z0-9#]+)*\/?(\?[a-zA-Z0-9-_]+=[a-zA-Z0-9-%]+&?)?$/;
    // a.map(x=>console.log(x+" => "+re.test(x)));
    </script>
    <script>
    function copyAddress(){
        var permanent_address= $.trim($("#permanent_address").val());
        console.log(permanent_address);
        $("#current_address").val(permanent_address);
    }
    </script>
@endpush

resources/views/home.blade.php
@extends('master1')
@section('title')
{{Auth::user()->name}}
@stop

@section('content')
  @push('css')
    <style>
      input[type=number]::-webkit-inner-spin-button, 
      input[type=number]::-webkit-outer-spin-button { 
          -webkit-appearance: none;
          -moz-appearance: none;
          appearance: none;
          margin: 0; 
      }
    </style>
    <style>
      
      </style>
  @endpush
    <div class="page-header page-header-small" style="background-image: url({{ asset('assets/img/sections/rodrigo-ardilha.jpg')}});">
      <div class="filter"></div>
    </div>
    <div class="wrapper">
      <div class="profile-content section">
        <div class="container">
          <div class="row">
            <div class="profile-picture">
              <div class="fileinput fileinput-new" data-provides="fileinput">
                <div class="fileinput-new img-no-padding">
                  {{-- <img src="../assets/img/faces/joe-gardner-2.jpg" alt="..."> --}}
                  @if(Auth::user()->image=='#')
                  <img src="{{asset("images/user/user_male.png")}}" class="img-circle img-responsive img-no-padding" alt="{!! Auth::user()->name !!}">
                  @else
                    <img src="{{asset( Auth::user()->image )}}" class="img-circle img-responsive img-no-padding" alt="{!! Auth::user()->name !!}">
                  @endif
                </div>
                <div class="name">
                  <h4 class="title text-center">{{Auth::user()->name}}
                    <br />
                    <small>{{Auth::user()->job}}</small>
                  </h4>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 ml-auto mr-auto text-center">
              <p>{!! Auth::user()->about !!} </p>
              @php
                  $sessions = Tracker::sessions(60 * 24); // get sessions (visits) from the past day
                  $visitor = Tracker::currentSession();
                  var_dump( $visitor->device->platform );


              @endphp
             {{$visitor}}
              <br />
              <a href="/edit-profile" class="btn btn-outline-default btn-round"><i class="fa fa-cog"></i> Settings</a>
              <button class="btn btn-outline-default btn-round" id="start"><i class="fa fa-cog"></i> start</button>
            </div>
          </div>
          <br/>
          {{-- attendance checkbox  --}}
          {{-- <input type="checkbox" id="attendance"> --}}
          <div class="nav-tabs-navigation">
            <div class="nav-tabs-wrapper">
              <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item">
                  <a class="nav-link active" data-toggle="tab" href="#profile" role="tab">Profile</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#about" role="tab">About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#education" role="tab">Education</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#skills" role="tab">Skills</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" data-toggle="tab" href="#experience" role="tab">Experience</a>
                </li>
              </ul>
            </div>
          </div>
         
          <!-- Tab panes -->
          <div class="tab-content">
            @include('tab.profile')
            @include('tab.about')
            @include('tab.education')
            @include('tab.skills')
            @include('tab.experience')
          </div>
        </div>
      </div>
    </div>
    @include('models.highSchool')
    @include('models.intermediate')
    @include('models.graduation')
    @include('models.masters')
    @include('models.diploma')
    @include('models.skills')
    @include('models.about')

    @include('models.experience.experience')
    @include('models.warning')
    @include('models.success')
@endsection

@push('scripts')
  @include('scripts.highSchool')
  @include('scripts.intermediate')
  @include('scripts.graduation')
  @include('scripts.masters')
  @include('scripts.diploma')
  @include('scripts.experience')
  @include('scripts.skills')
  @include('scripts.about')
  <script>
      $("#addAbout").click(function(){
        var about = $("#about").val();
        
        $.ajaxSetup({
          headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}
        });
    
        $.ajax({
          type:"GET",
          url:"{{url('add-about')}}",
          data:{
            'about': about,
          }, 
        
          success:function(res){ 
            $("#descriptionModal").hide();
          }
        });
      }); 
  </script>
  <script>
  $("#editAbout").click(function(){
      $('#descriptionModal').show();
  });
  $("#editAboutClose").click(function(){
      $('#descriptionModal').hide();
  });
  $("#addAboutModal").click(function(){
      $('#userinfoModal').show();
  });
  $("#addaboutModalClose").click(function(){
      $('#userinfoModal').hide();
  });
  $("#addProffessionalSkill").click(function(){
      $('#professionalSkill').show();
  });
  $("#addProffessionalSkillClose").click(function(){
      $('#professionalSkill').hide();
  });

  var percentage_old = $('#percentage').val();
  $('#percentage').change(function(){
    var percentage = $('#percentage').val();
    console.log(percentage);
    if(percentage>100){
      $("#warning").modal('show');
      $('#percentage').val(percentage_old);
  }
  });
  </script>

  <script>
  if (location.hash) {
  $('a[href=\'' + location.hash + '\']').tab('show');
}
var activeTab = localStorage.getItem('activeTab');
if (activeTab) {
  $('a[href="' + activeTab + '"]').tab('show');
}

$('body').on('click', 'a[data-toggle=\'tab\']', function (e) {
  e.preventDefault()
  var tab_name = this.getAttribute('href')
  if (history.pushState) {
    history.pushState(null, null, tab_name)
  }
  else {
    location.hash = tab_name
  }
  localStorage.setItem('activeTab', tab_name)

  $(this).tab('show');
  return false;
});
$(window).on('popstate', function () {
  var anchor = location.hash ||
    $('a[data-toggle=\'tab\']').first().attr('href');
  $('a[href=\'' + anchor + '\']').tab('show');
});
</script>
<script>
$("#attendance").change(function(){
      $.ajaxSetup({
        headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}
      });
      $.ajax({
        type:"GET",
        url:"{{url('make-attandance')}}",
        success:function(data){ 
          console.log(data);
          $.growl.notice({ message: "Done !" });
        }
      });
})
</script>
@stack('js')
@endpush